//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThatOneStore.FruitShopReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/FruitShop")]
    [System.SerializableAttribute()]
    public partial class ProductType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThatOneStore.FruitShopReference.ProductDetails ProductDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThatOneStore.FruitShopReference.ProductDetails ProductDetails {
            get {
                return this.ProductDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDetailsField, value) != true)) {
                    this.ProductDetailsField = value;
                    this.RaisePropertyChanged("ProductDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetails", Namespace="http://schemas.datacontract.org/2004/07/FruitShop")]
    [System.SerializableAttribute()]
    public partial class ProductDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetails", Namespace="http://schemas.datacontract.org/2004/07/FruitShop")]
    [System.SerializableAttribute()]
    public partial class LoginDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/FruitShop")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OwnedProductType", Namespace="http://schemas.datacontract.org/2004/07/FruitShop")]
    [System.SerializableAttribute()]
    public partial class OwnedProductType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThatOneStore.FruitShopReference.ProductDetails ProductDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThatOneStore.FruitShopReference.ProductDetails ProductDetails {
            get {
                return this.ProductDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDetailsField, value) != true)) {
                    this.ProductDetailsField = value;
                    this.RaisePropertyChanged("ProductDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FruitShopReference.IFruitShop")]
    public interface IFruitShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetAvailableProducts", ReplyAction="http://tempuri.org/IFruitShop/GetAvailableProductsResponse")]
        ThatOneStore.FruitShopReference.ProductType[] GetAvailableProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetAvailableProducts", ReplyAction="http://tempuri.org/IFruitShop/GetAvailableProductsResponse")]
        System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.ProductType[]> GetAvailableProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/RegisterUser", ReplyAction="http://tempuri.org/IFruitShop/RegisterUserResponse")]
        ThatOneStore.FruitShopReference.Message RegisterUser(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/RegisterUser", ReplyAction="http://tempuri.org/IFruitShop/RegisterUserResponse")]
        System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.Message> RegisterUserAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/LoginCustomer", ReplyAction="http://tempuri.org/IFruitShop/LoginCustomerResponse")]
        bool LoginCustomer(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/LoginCustomer", ReplyAction="http://tempuri.org/IFruitShop/LoginCustomerResponse")]
        System.Threading.Tasks.Task<bool> LoginCustomerAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/AddProduct", ReplyAction="http://tempuri.org/IFruitShop/AddProductResponse")]
        int AddProduct(ThatOneStore.FruitShopReference.LoginDetails loginDetails, ThatOneStore.FruitShopReference.ProductDetails productDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/AddProduct", ReplyAction="http://tempuri.org/IFruitShop/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails, ThatOneStore.FruitShopReference.ProductDetails productDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/BuyProduct", ReplyAction="http://tempuri.org/IFruitShop/BuyProductResponse")]
        ThatOneStore.FruitShopReference.Message BuyProduct(ThatOneStore.FruitShopReference.LoginDetails loginDetails, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/BuyProduct", ReplyAction="http://tempuri.org/IFruitShop/BuyProductResponse")]
        System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.Message> BuyProductAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetBoughtProducts", ReplyAction="http://tempuri.org/IFruitShop/GetBoughtProductsResponse")]
        ThatOneStore.FruitShopReference.OwnedProductType[] GetBoughtProducts(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetBoughtProducts", ReplyAction="http://tempuri.org/IFruitShop/GetBoughtProductsResponse")]
        System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.OwnedProductType[]> GetBoughtProductsAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetBalance", ReplyAction="http://tempuri.org/IFruitShop/GetBalanceResponse")]
        double GetBalance(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShop/GetBalance", ReplyAction="http://tempuri.org/IFruitShop/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFruitShopChannel : ThatOneStore.FruitShopReference.IFruitShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FruitShopClient : System.ServiceModel.ClientBase<ThatOneStore.FruitShopReference.IFruitShop>, ThatOneStore.FruitShopReference.IFruitShop {
        
        public FruitShopClient() {
        }
        
        public FruitShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FruitShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ThatOneStore.FruitShopReference.ProductType[] GetAvailableProducts() {
            return base.Channel.GetAvailableProducts();
        }
        
        public System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.ProductType[]> GetAvailableProductsAsync() {
            return base.Channel.GetAvailableProductsAsync();
        }
        
        public ThatOneStore.FruitShopReference.Message RegisterUser(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.RegisterUser(loginDetails);
        }
        
        public System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.Message> RegisterUserAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.RegisterUserAsync(loginDetails);
        }
        
        public bool LoginCustomer(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.LoginCustomer(loginDetails);
        }
        
        public System.Threading.Tasks.Task<bool> LoginCustomerAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.LoginCustomerAsync(loginDetails);
        }
        
        public int AddProduct(ThatOneStore.FruitShopReference.LoginDetails loginDetails, ThatOneStore.FruitShopReference.ProductDetails productDetails) {
            return base.Channel.AddProduct(loginDetails, productDetails);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails, ThatOneStore.FruitShopReference.ProductDetails productDetails) {
            return base.Channel.AddProductAsync(loginDetails, productDetails);
        }
        
        public ThatOneStore.FruitShopReference.Message BuyProduct(ThatOneStore.FruitShopReference.LoginDetails loginDetails, int productId) {
            return base.Channel.BuyProduct(loginDetails, productId);
        }
        
        public System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.Message> BuyProductAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails, int productId) {
            return base.Channel.BuyProductAsync(loginDetails, productId);
        }
        
        public ThatOneStore.FruitShopReference.OwnedProductType[] GetBoughtProducts(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.GetBoughtProducts(loginDetails);
        }
        
        public System.Threading.Tasks.Task<ThatOneStore.FruitShopReference.OwnedProductType[]> GetBoughtProductsAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.GetBoughtProductsAsync(loginDetails);
        }
        
        public double GetBalance(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.GetBalance(loginDetails);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync(ThatOneStore.FruitShopReference.LoginDetails loginDetails) {
            return base.Channel.GetBalanceAsync(loginDetails);
        }
    }
}
